site_name: MQTT-based PackML IoT Agent
site_url: https://github.com/demkoen/DIH2-Phase3
repo_url: https://github.com/demkoen/DIH2-Phase3
site_description: MQTT-based PackML IoT Agent Documentation
docs_dir: docs
site_dir: html
markdown_extensions: [toc,fenced_code]
use_directory_urls: true
theme: readthedocs
nav:
  - Home: 'README.md'
  - Step by Step: 
    - 'Tutorial' : 'step_by_step_tutorial.md'
    - 'Docker configuration' : 'docker-README.md'
  - User & Programmers Manual:
    - 'Architecture' : 'architecture.md'
    - 'User Guide': 'usermanual.md'
    - 'API' : 'api.md'
  - 'Installation & Administration Manual':
    - 'Installation Guide': 'installationguide.md'
